<?php

/**
 * @package     Metagen
 * @subpackage  Generator
 *
 * @copyright   Copyright (C) Yepr, Herman Peeren. All rights reserved.
 * @license     GNU General Public License version 3 or later; see LICENSE.txt
 */

declare(strict_types=1);

namespace Yepr\Component\Metagen\Administrator\Generator\Meta;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects

/**
 * The text on a generated language's forms, collected while they are built.
 *
 * Every label a generated form carries is a constant, and until 3.3 nothing
 * defined any of them - so a generated form rendered its own constant names
 * back at the person filling it in. This is the other half.
 *
 * **Not `LanguageStringUtil`, and that is structural rather than a
 * preference.** The old Extengen collected strings with a Twig *function*,
 * `addLanguageString`, called from inside a template as it rendered - which is
 * why `LanguageFiles` had to run last in `Joomla6Target`. Meta-gen's forms
 * generator renders no templates at all; it builds XML through DOM, which is
 * the line 2.1 drew. There is no render pass to collect during. And
 * `initLangTree()` reads `$AST->extensions->component->languages`, a
 * *project's* translation list; a metalanguage has no `extensions` node at all,
 * so that tree comes out empty and the first call fatals. It stays where it is,
 * generating a component's strings.
 *
 * So the collection happens here instead, in the one place that knows both a
 * constant and the text behind it: `FormXml` asks for a constant and hands over
 * the words at the same moment, which is the only arrangement in which the two
 * cannot drift.
 *
 * @since  1.3.0
 */
final class LanguageStrings
{
    /**
     * Constant name to the text behind it.
     *
     * @var array<string, string>
     *
     * @since  1.3.0
     */
    private array $strings = [];

    /**
     * Constants asked for twice with different words, and both answers.
     *
     * @var array<string, string[]>
     *
     * @since  1.3.0
     */
    private array $clashes = [];

    /**
     * Record a constant and the text it stands for.
     *
     * The first text wins. Two different labels under one constant is a
     * language whose forms disagree with each other, and picking the later one
     * would make the winner depend on the order classifiers happen to be
     * walked in - so the clash is kept and reported rather than resolved.
     *
     * @since  1.3.0
     */
    public function add(string $constant, string $text): string
    {
        if (!isset($this->strings[$constant])) {
            $this->strings[$constant] = $text;

            return $constant;
        }

        if ($this->strings[$constant] !== $text) {
            $this->clashes[$constant] = array_values(array_unique(
                [...($this->clashes[$constant] ?? [$this->strings[$constant]]), $text]
            ));
        }

        return $constant;
    }

    /**
     * Every constant collected, in the order a person reads a file in.
     *
     * @return array<string, string>
     *
     * @since  1.3.0
     */
    public function all(): array
    {
        $strings = $this->strings;

        ksort($strings);

        return $strings;
    }

    /**
     * Constants two different labels were offered for.
     *
     * @return array<string, string[]>
     *
     * @since  1.3.0
     */
    public function clashes(): array
    {
        return $this->clashes;
    }

    /**
     * How many strings were collected.
     *
     * @since  1.3.0
     */
    public function count(): int
    {
        return \count($this->strings);
    }

    /**
     * The whole thing as a Joomla language file.
     *
     * @param   string  $title  What the file says it is, in its first line.
     *
     * @since  1.3.0
     */
    public function render(string $title): string
    {
        $lines = [
            '; ' . $title,
            '; Generated by Meta-gen. Every label on this language\'s forms, and nothing else.',
            '',
        ];

        foreach ($this->all() as $constant => $text) {
            $lines[] = $constant . '="' . self::escape($text) . '"';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * One value, in the form Joomla's ini parser reads back unchanged.
     *
     * A double quote inside a value is written `\"`. That is not a general ini
     * escape - `parse_ini_string` is called with `INI_SCANNER_RAW`, which
     * leaves the two characters alone - it is a convention Joomla undoes
     * itself, in one `str_replace` at the end of
     * `LanguageHelper::parseIniFile()`. The Joomla 3 spelling, `"_QQ_"`, is
     * gone: written that way the marker arrives in the string verbatim.
     *
     * A newline ends the entry, so one cannot be in a value at all; a label
     * somebody typed a line break into becomes a space rather than a file that
     * silently loses every string after it.
     *
     * @since  1.3.0
     */
    public static function escape(string $text): string
    {
        $text = (string) preg_replace('/\s+/u', ' ', $text);

        return str_replace('"', '\\"', trim($text));
    }
}
